# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: insmessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='insmessage.proto',
  package='raven.fcu.swicd',
  syntax='proto3',
  serialized_pb=_b('\n\x10insmessage.proto\x12\x0fraven.fcu.swicd\"\x8d\x04\n\x19RavenFCU_SWICD_INSmessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x01\x12\x0c\n\x04roll\x18\x05 \x01(\x02\x12\r\n\x05pitch\x18\x06 \x01(\x02\x12\x0b\n\x03yaw\x18\x07 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x08 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\t \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\n \x01(\x02\x12\x11\n\tbarometer\x18\x0b \x01(\x02\x12\x0e\n\x06\x63ourse\x18\x0c \x01(\x02\x12\r\n\x05speed\x18\r \x01(\x02\x12\x11\n\tvelocityN\x18\x0e \x01(\x02\x12\x11\n\tvelocityE\x18\x0f \x01(\x02\x12\x11\n\tvelocityD\x18\x10 \x01(\x02\x12\x0f\n\x07numSats\x18\x11 \x01(\x05\x12\x13\n\x0b\x64\x65\x63lination\x18\x12 \x01(\x02\x12\x42\n\x06gpsFix\x18\x13 \x01(\x0e\x32\x32.raven.fcu.swicd.RavenFCU_SWICD_INSmessage.FixType\"t\n\x07\x46ixType\x12\x0e\n\nGPS_NO_FIX\x10\x00\x12\x16\n\x12GPS_DEAD_RECKONING\x10\x01\x12\n\n\x06GPS_2D\x10\x02\x12\n\n\x06GPS_3D\x10\x03\x12\x16\n\x12GPS_GNSS_DEAD_RECK\x10\x04\x12\x11\n\rGPS_TIME_ONLY\x10\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RAVENFCU_SWICD_INSMESSAGE_FIXTYPE = _descriptor.EnumDescriptor(
  name='FixType',
  full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.FixType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GPS_NO_FIX', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPS_DEAD_RECKONING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPS_2D', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPS_3D', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPS_GNSS_DEAD_RECK', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPS_TIME_ONLY', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=447,
  serialized_end=563,
)
_sym_db.RegisterEnumDescriptor(_RAVENFCU_SWICD_INSMESSAGE_FIXTYPE)


_RAVENFCU_SWICD_INSMESSAGE = _descriptor.Descriptor(
  name='RavenFCU_SWICD_INSmessage',
  full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.altitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roll', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.roll', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.pitch', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.yaw', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accel_x', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.accel_x', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accel_y', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.accel_y', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accel_z', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.accel_z', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='barometer', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.barometer', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='course', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.course', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.speed', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocityN', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.velocityN', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocityE', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.velocityE', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocityD', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.velocityD', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numSats', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.numSats', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='declination', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.declination', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gpsFix', full_name='raven.fcu.swicd.RavenFCU_SWICD_INSmessage.gpsFix', index=18,
      number=19, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RAVENFCU_SWICD_INSMESSAGE_FIXTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=563,
)

_RAVENFCU_SWICD_INSMESSAGE.fields_by_name['gpsFix'].enum_type = _RAVENFCU_SWICD_INSMESSAGE_FIXTYPE
_RAVENFCU_SWICD_INSMESSAGE_FIXTYPE.containing_type = _RAVENFCU_SWICD_INSMESSAGE
DESCRIPTOR.message_types_by_name['RavenFCU_SWICD_INSmessage'] = _RAVENFCU_SWICD_INSMESSAGE

RavenFCU_SWICD_INSmessage = _reflection.GeneratedProtocolMessageType('RavenFCU_SWICD_INSmessage', (_message.Message,), dict(
  DESCRIPTOR = _RAVENFCU_SWICD_INSMESSAGE,
  __module__ = 'insmessage_pb2'
  # @@protoc_insertion_point(class_scope:raven.fcu.swicd.RavenFCU_SWICD_INSmessage)
  ))
_sym_db.RegisterMessage(RavenFCU_SWICD_INSmessage)


# @@protoc_insertion_point(module_scope)
