# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloadmessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payloadmessage.proto',
  package='raven.fcu.swicd',
  syntax='proto3',
  serialized_pb=_b('\n\x14payloadmessage.proto\x12\x0fraven.fcu.swicd\"_\n\x1dRavenFCU_SWICD_PayloadMessage\x12\x15\n\rmessageSentTS\x18\x01 \x01(\x01\x12\x19\n\x11messageReceivedTS\x18\x02 \x01(\x01\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RAVENFCU_SWICD_PAYLOADMESSAGE = _descriptor.Descriptor(
  name='RavenFCU_SWICD_PayloadMessage',
  full_name='raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageSentTS', full_name='raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.messageSentTS', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messageReceivedTS', full_name='raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.messageReceivedTS', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['RavenFCU_SWICD_PayloadMessage'] = _RAVENFCU_SWICD_PAYLOADMESSAGE

RavenFCU_SWICD_PayloadMessage = _reflection.GeneratedProtocolMessageType('RavenFCU_SWICD_PayloadMessage', (_message.Message,), dict(
  DESCRIPTOR = _RAVENFCU_SWICD_PAYLOADMESSAGE,
  __module__ = 'payloadmessage_pb2'
  # @@protoc_insertion_point(class_scope:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
  ))
_sym_db.RegisterMessage(RavenFCU_SWICD_PayloadMessage)


# @@protoc_insertion_point(module_scope)
